### ISSUE TITLE
Add contributes

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_utils#18]
Add contributes files to this repo

**Comment by peterdudfield** [comment]
@all-contributors please add @peterdudfield  for code

**Comment by peterdudfield** [comment]
@all-contributors please add @jacobbieker for code
@all-contributors please add @JackKelly  for code

**Comment by peterdudfield** [comment]
@all-contributors please add @jacobbieker for code

**Comment by peterdudfield** [comment]
@all-contributors please add @JackKelly for code

**Comment by peterdudfield** [comment]
@all-contributors please add @JackKelly for code

**Comment by peterdudfield** [comment]
@all-contributors please add @JackKelly for code

**Comment by JackKelly** [comment]
Thanks loads for adding us, @peterdudfield!

This little conversation between you and the bot made me smile!
