### ISSUE TITLE
Add coverage badge to Readme

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_utils#31]
## Detailed Description
Add a coverage badge from the unitest to the main Readme.md file

## Context
- nice to see what the coverage is like - and for other people to see

**Comment by Khushi-agarwal** [comment]
@peterdudfield can I work on this issue.

**Comment by peterdudfield** [comment]
Hi @Khushi-agarwal, I hope its ok. I went ahead and used codecov for this
