### ISSUE TITLE
Update validation csv

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_utils#62]
## Detailed Description
Update columns to https://github.com/openclimatefix/predict_pv_yield/pull/96#issuecomment-981546725

**Comment by JackKelly** [comment]
Thanks!  Sorry for not commenting on your PR earlier!

**Comment by peterdudfield** [comment]
> openclimatefix/predict_pv_yield#96 (comment)

Just all part of the 'dev' cycle

**Comment by peterdudfield** [comment]
Columns:

* `t0_datetime_utc`
* `target_datetime_utc`   :The datetime the forecast is _about_.  i.e. `t0_datetime_utc + (forecast_timestep_i * forecast_sample_period)`
* `forecast_GSP_PV_outturn_MW`
* `actual_GSP_PV_outturn_MW`
* `GSP_ID`
* `batch_index` (optional, but useful for debugging)
* `example_index` (optional, but useful for debugging)


Although Ill try to use all lower case letters

**Comment by JackKelly** [comment]
SGTM
