### ISSUE TITLE
Add custom loss functions

### ISSUE THREAD

**Issue by jacobbieker** [openclimatefix/nowcasting_utils#7]

**Comment by peterdudfield** [comment]
feel to use

https://github.com/openclimatefix/predict_pv_yield/blob/master/predict_pv_yield/models/metrics.py
https://github.com/openclimatefix/predict_pv_yield/blob/master/predict_pv_yield/models/loss.py
if you want

**Comment by peterdudfield** [comment]
Ive started a branch - https://github.com/openclimatefix/nowcasting_utils/tree/issue/7-metrics-losses

**Comment by peterdudfield** [comment]
@jacobbieker are there any others you would like to add here?

**Comment by jacobbieker** [comment]
I might move more losses from SatFlow into here as well, but that is great for now!

**Comment by peterdudfield** [comment]
ok - i made this issue to keep track of it - https://github.com/openclimatefix/nowcasting_utils/issues/13
