### ISSUE TITLE
Add National MAE

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting_utils#72]
## Detailed Description
When evaluation results, add National MAE. 

see https://github.com/openclimatefix/nowcasting_utils/pull/68#issuecomment-984731765

## Context
national = sum(gsp)
current test dataset doesnt have all gsp id for all datetimes, so we would need this in order to run this stats

**Comment by JackKelly** [comment]
> current test dataset doesnt have all gsp id for all datetimes

ah, good catch, I'd forgotten that!

**Comment by peterdudfield** [comment]
done in #75
